admin_users_index:
    path: /
    controller: App\Controller\Admin\AdminController::indexUsers

admin_users_list:
    path: /users
    controller: App\Controller\Admin\AdminController::listUsers

admin_user_edit:
    path: /user/{id}/edit
    controller: App\Controller\Admin\AdminController::editUserRoles

admin_dashboard:
    path: /dashboard
    controller: App\Controller\Admin\AdminController::dashboard