app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::editProfile

app_customer_profile:
    path: /customer-profile
    controller: App\Controller\CustomerProfileController::edit

app_dashboard:
    path: /profile
    controller: App\Controller\ProfileController::editProfile

app_forgot_password:
    path: /register
    controller: App\Controller\RegistrationController::register