<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260320163003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE subscription (price_snapshot NUMERIC(10, 2) NOT NULL, currency_snapshot VARCHAR(3) DEFAULT NULL, billing_interval_snapshot VARCHAR(10) NOT NULL, discount_percent_snapshot NUMERIC(5, 2) DEFAULT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, next_billing_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paused_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trial_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, subscription_plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3C664D3A76ED395 ON subscription (user_id)');
        $this->addSql('CREATE INDEX IDX_A3C664D39B8CE200 ON subscription (subscription_plan_id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D39B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id)');
        $this->addSql('ALTER TABLE subscription_plan ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE subscription_plan ALTER is_active SET NOT NULL');
        $this->addSql('ALTER TABLE subscription_plan ALTER is_featured DROP DEFAULT');
        $this->addSql('ALTER TABLE subscription_plan ALTER updated_at DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3A76ED395');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D39B8CE200');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('ALTER TABLE subscription_plan ALTER is_active SET DEFAULT true');
        $this->addSql('ALTER TABLE subscription_plan ALTER is_active DROP NOT NULL');
        $this->addSql('ALTER TABLE subscription_plan ALTER is_featured SET DEFAULT false');
        $this->addSql('ALTER TABLE subscription_plan ALTER updated_at SET NOT NULL');
    }
}
