homepage:
   path: /
   controller: App\Controller\DefaultController::homepage

user_routes:
   resource: "routes/user.yaml"
   type: "yaml"

admin_routes:
   resource: "routes/admin.yaml"
   type: "yaml"
   prefix: /admin

subscription_plan_routes:
   resource: "routes/subscription-plan.yaml"
   type: "yaml"
   prefix: /admin/subscription-plan

subscription_routes:
   resource: "routes/subscription.yaml"
   type: "yaml"
   prefix: /subscription

api_payment_routes:
   resource: "routes/api_payments.yaml"
   type: "yaml"
   prefix: /api/payments

payment_routes:
   resource: "routes/payment.yaml"
   type: "yaml"
   prefix: /payments

invoice_routes:
   resource: "routes/invoice.yaml"
   type: "yaml"
   prefix: /invoices